name: Deploy workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #Checkout Repo
        with:
          submodules: recursive
      - uses: actions/setup-node@v4 #Setup Node
        with:
          node-version: 20
      - name: Install Microsoft Edge
        run: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft-archive-keyring.gpg && sudo mv microsoft-archive-keyring.gpg /usr/share/keyrings/ && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge-stable.list && sudo apt update && sudo apt install -y microsoft-edge-stable
      - name: Run Karma Tests
        run: |
          cd ./frontend && npm i && npm run test

  server-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache: false

      - name: Lint
        run: |
          cd ./server && make check

  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache: false

      - name: Test
        run: |
          cd ./server && make test-verbose

  deploy:
    needs: [frontend-test, server-test, server-lint]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy by SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          command_timeout: 60m
          script: |
            cd ${{secrets.PROJECT_FOLDER}};
            git pull;
            make prod;
